### ISSUE TITLE
Size of futlength

### ISSUE THREAD

**Issue by mtk380** [Xiaoyu006/GNN-RNN-Based-Trajectory-Prediction-ITSC2021#1]
Great job! I want to know why the val loss output is a 10 dim tensor, what does that mean? When i change the futlength to 50, some errors occurred.

**Comment by Xiaoyu006** [comment]
Hi, the future length is 5 seconds. The original data is sampled at 10Hz, while in training, the predictor downsamples the future trajectory into 2Hz. So that 10 dim tensor means the locations at [0.5, 1.0, 1.5,..., 5.0] seconds.

Hope the above answers this question.
